version: '3.8'

services:
  grafana:
    ports:
      - "3000:3000"
    volumes:
      - ./plugin/anglerfishlyy-llmwatch-panel/dist:/var/lib/grafana/plugins/anglerfishlyy-llmwatch-panel
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=anglerfishlyy-llmwatch-panel
